#!/usr/bin/env python3
"""Generate the «кто свёл» reference: per-track SEO pages + grouped hub.

Each track carries a credited role from roles.json (mix / mm / master):
detail pages and schema state only what we actually did. The hub groups by
primary (first-credited) artist with a canonical name, so an artist never
appears as two sections (e.g. «Дима Билан» / «Dima Bilan»).

Besides track/**, sitemap.xml and track-info.json, a run also normalises the
hand-written pages from the same data, so facts can't drift between them:
  - index.html: cover alts and the JSON-LD catalogue are rewritten from
    roles.json (patch_index_roles); the studio entity is typed Organization
    with two founder Person nodes (fix_studio_graph).
  - faq/index.html: <span data-n="works|artists"> counters, the studio
    entity, then sync_faq_schema.main() re-copies the answers into FAQPage.
  - llms.txt: the «N избранных работ для M артистов» phrase.
  - en/**: at the end main() runs build_en.py (same interpreter, cwd=repo),
    which mirrors index / hub / faq / every live track page under /en/ from
    the dictionaries in i18n/en/. Pass --no-en to skip it. The hreflang links
    on the RU side are emitted for exactly that set of pages unconditionally
    (no dependency on en/** already existing, so a clean checkout builds in
    one pass); /tier/ has no EN twin and gets none.
Build order: python3 build_who_mixed.py (→ build_en.py) → build_tier.py
(lifts the FAQ shell and studio entity) → build_llms_full.py (reads the
rendered pages). build_en.py is lenient by default (new artists / stories
without a translation are reported in i18n/missing.txt, not fatal); run
`python3 build_en.py --strict` before a release to make them fatal.
"""

import hashlib
import html
import json
import re
import sys
from collections import OrderedDict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
INDEX = ROOT / "index.html"
TRACK_DIR = ROOT / "track"
ROLES_FILE = ROOT / "roles.json"
FEATS_FILE = ROOT / "feats.json"
NOTES_FILE = ROOT / "notes.json"
# persistent SEO ledger: last-known slug per track id, retired-slug redirects,
# and honest per-slug lastmod. Keeps URLs alive + sitemap dates truthful across
# full rebuilds. Committed to git so state survives between machines.
SEO_STATE_FILE = ROOT / "seo_state.json"
SITE = "https://credits.podlesnytwins.com"


def abs_img(u):
    """Site-relative cover paths -> absolute URLs for og:image / JSON-LD."""
    return f"{SITE}{u}" if u.startswith("/") else u
TODAY = date.today().isoformat()

# /faq/ is a hand-written page, not generated from track data. Bump this when the
# FAQ text itself changes — a rebuild must not fake freshness for untouched copy.
FAQ_LASTMOD = "2026-09-12"

# /tier/ is generated by build_tier.py from tier.json, not from track data —
# same rule as the FAQ: bump this when the tier list itself changes.
TIER_LASTMOD = "2026-09-10"

# canonical display name for spelling variants of the same artist
CANON = {"Dima Bilan": "Дима Билан", "LSP": "ЛСП"}
# «иностранный агент» artists — need * marker + footnote
IA = {"morgenshtern"}

GA_TAG = (
    '<!-- Google tag (gtag.js) -->\n'
    '<script async src="https://www.googletagmanager.com/gtag/js?id=G-JWPH35TTVX"></script>\n'
    '<script>\n'
    '  window.dataLayer = window.dataLayer || [];\n'
    '  function gtag(){dataLayer.push(arguments);}\n'
    "  gtag('js', new Date());\n"
    "  gtag('config', 'G-JWPH35TTVX');\n"
    '</script>'
)

ROLE_WORD = {"mm": "Сведение и мастеринг", "mix": "Сведение", "master": "Мастеринг"}
ROLE_VERB = {"mm": "Кто свёл", "mix": "Кто свёл", "master": "Кто мастерил"}
# schema.org Role.roleName on the home-page graph — bilingual, one per role
ROLE_NAME_LD = {
    "mm": "сведение и мастеринг (mixing & mastering engineer)",
    "mix": "сведение (mixing engineer)",
    "master": "мастеринг (mastering engineer)",
}
# tail of every cover <img alt> on the home page
ROLE_ALT = {
    "mm": "сведение и мастеринг Podlesny Twins",
    "mix": "сведение Podlesny Twins",
    "master": "мастеринг Podlesny Twins",
}
# album whose tracks carry different roles: name the release, claim no role
MIXED_ALT = "обложка релиза"

# ── the studio entity (one definition for every page's JSON-LD) ──────
#
# Podlesny Twins is a mixing/mastering studio, not a band. The graph on
# index.html, faq/index.html (and /tier/, which lifts the node from the FAQ)
# used to type it MusicGroup; a rebuild now normalises it to Organization
# with the two founders as stable Person nodes, so the type can't regress.
STUDIO_ID = f"{SITE}/#podlesnytwins"
FOUNDERS = [
    {"@type": "Person", "@id": f"{SITE}/#anton-podlesny",
     "name": "Антон Подлесный", "alternateName": "Anton Podlesny",
     "jobTitle": "Звукорежиссёр", "worksFor": {"@id": STUDIO_ID}},
    {"@type": "Person", "@id": f"{SITE}/#pavel-podlesny",
     "name": "Павел Подлесный", "alternateName": "Pavel Podlesny",
     "jobTitle": "Звукорежиссёр", "worksFor": {"@id": STUDIO_ID}},
]
# properties that only make sense on a MusicGroup (or are replaced by founder)
MUSICGROUP_ONLY = ("genre", "member", "album", "track", "musicGroupMember")


def fix_studio_graph(graph: list[dict]) -> list[dict]:
    """Normalise the studio node in a page's @graph and add the founders.

    Idempotent: keeps @id, name, alternateName, url, sameAs, description,
    foundingDate/Location and anything else page-specific; only the type,
    the MusicGroup-only keys and the founder links change.
    """
    idx = next((i for i, n in enumerate(graph) if n.get("@id") == STUDIO_ID), None)
    if idx is None:
        raise SystemExit(f"studio node {STUDIO_ID} not found in JSON-LD graph")
    node = graph[idx]
    node["@type"] = "Organization"
    for key in MUSICGROUP_ONLY:
        node.pop(key, None)
    node["founder"] = [{"@id": p["@id"]} for p in FOUNDERS]
    present = {n.get("@id") for n in graph}
    persons = [dict(p) for p in FOUNDERS if p["@id"] not in present]
    # founders sit right after the studio; existing Person nodes stay put
    return graph[: idx + 1] + persons + graph[idx + 1:]


def plural(n: int, one: str, few: str, many: str) -> str:
    """Russian plural: 1 артист, 2 артиста, 5 артистов, 11 артистов."""
    if n % 10 == 1 and n % 100 != 11:
        return one
    if 2 <= n % 10 <= 4 and not 12 <= n % 100 <= 14:
        return few
    return many


def catalog_counts(tracks: list[dict]) -> dict:
    """The two public catalogue metrics, computed once for every page.

    recordings — publishedRecordingsCount: unique published tracks (unique
        Spotify ids after tile/album dedup; an album container is not a
        recording and is not counted).
    artists — creditedArtistsCount: unique artists credited anywhere in the
        catalogue — primary artists, collab partners in the artist field
        ("MACAN, NAVAI" → both) and featured artists from feats.json —
        after CANON spelling-variant merging and «*» marker stripping.
    groups — artistGroupsCount: sections of the /track/ hub, i.e. unique
        primary (first-credited) artists. Smaller than `artists` by design.
    """
    return {
        "recordings": len({tr["id"] for tr in tracks}),
        "artists": len(credited_artists(tracks)),
        "groups": len({primary_of(tr["artist"]) for tr in tracks}),
    }


def credited_artists(tracks: list[dict]) -> list[str]:
    """Every artist credited in the catalogue (see catalog_counts), sorted."""
    names: set[str] = set()
    for tr in tracks:
        names.update(canon(x) for x in tr["artist"].split(", "))
        names.update(feat_of(tr))
    names.discard("")
    return sorted(names, key=str.casefold)


def load_tracks() -> list[dict]:
    """The catalogue as other generators should see it: parsed from
    index.html + roles.json, slugs assigned. build_llms_full.py uses it."""
    global NOTES
    NOTES = load_notes()
    tracks = extract_tracks(INDEX.read_text(encoding="utf-8"), load_roles())
    assign_slugs(tracks)
    return tracks


# ── EN mirror (Phase 2) ─────────────────────────────────────────────
#
# build_en.py mirrors the RU pages under /en/<same path>/: the home page, the
# hub, the FAQ and every live (non-redirect) track page — and nothing else
# (/tier/ stays RU-only). Each RU page points at its EN twin (hreflang) and
# the sitemap lists the EN URLs for exactly that set. This is decided here,
# not by looking at en/** on disk: main() runs build_en.py at the end, so a
# clean checkout builds both sides in one pass with no bootstrap order.
EMIT_EN = True  # Phase 2: /en/ mirror is live (build_en.py)
EN_DIR = ROOT / "en"
EN_STATIC = {"", "track/", "faq/"}


def en_exists(rel: str) -> bool:
    """Does build_en.py produce /en/<rel>? rel is the site-relative directory:
    "" for the home, "track/", "track/<slug>/", "faq/". Redirect stubs are
    rendered by render_redirect (no hreflang) and never reach this check."""
    if not EMIT_EN:
        return False
    return rel in EN_STATIC or bool(re.fullmatch(r"track/[^/]+/", rel))


def hreflang_links(rel: str) -> str:
    """<link rel=alternate hreflang> block for a RU page, or "" if no EN twin."""
    if not en_exists(rel):
        return ""
    ru, en = f"{SITE}/{rel}", f"{SITE}/en/{rel}"
    return (
        f'<link rel="alternate" hreflang="ru" href="{ru}">\n'
        f'<link rel="alternate" hreflang="en" href="{en}">\n'
        f'<link rel="alternate" hreflang="x-default" href="{en}">\n'
    )


HREFLANG_RE = re.compile(r'\n?<link rel="alternate" hreflang="[^"]*" href="[^"]*"\s*/?>')


def patch_hreflang(doc: str, rel: str) -> str:
    """Hand-written pages (index.html, faq/index.html): drop whatever hreflang
    links are there and re-emit the current set right after the canonical —
    the same anchor build_en.py uses on the EN side, so the two mirror."""
    doc = HREFLANG_RE.sub("", doc)
    links = hreflang_links(rel)
    if not links:
        return doc
    return re.sub(r'(<link rel="canonical" href="[^"]*">)',
                  lambda m: m.group(1) + "\n" + links.rstrip("\n"), doc, count=1)

TRANSLIT = {
    "а": "a", "б": "b", "в": "v", "г": "g", "д": "d", "е": "e", "ё": "yo",
    "ж": "zh", "з": "z", "и": "i", "й": "y", "к": "k", "л": "l", "м": "m",
    "н": "n", "о": "o", "п": "p", "р": "r", "с": "s", "т": "t", "у": "u",
    "ф": "f", "х": "h", "ц": "ts", "ч": "ch", "ш": "sh", "щ": "sch",
    "ъ": "", "ы": "y", "ь": "", "э": "e", "ю": "yu", "я": "ya",
}


def esc(s: str) -> str:
    return html.escape(s, quote=True)


def slugify(*parts: str) -> str:
    raw = "-".join(parts).lower().replace("’", "'")
    out = []
    for ch in raw:
        if ch in TRANSLIT:
            out.append(TRANSLIT[ch])
        elif "a" <= ch <= "z" or "0" <= ch <= "9":
            out.append(ch)
        elif ch in " -_'/;,&.+":
            out.append("-")
    slug = re.sub(r"-+", "-", "".join(out)).strip("-")
    return slug[:80] or "track"


def canon(name: str) -> str:
    """Canonical display name for a single artist token."""
    n = name.replace("*", "").strip()
    return CANON.get(n, n)


def is_ia(name: str) -> bool:
    return name.replace("*", "").strip().lower() in IA


def primary_of(artist: str) -> str:
    return canon(artist.split(", ")[0])


def others_of(artist: str) -> list[str]:
    return [canon(x) for x in artist.split(", ")[1:]]


def feat_of(tr: dict) -> list[str]:
    """Per-track featured artists. Album tracks: explicit `feat` field
    (string or list). Singles: fall back to non-primary artists in `artist`."""
    f = tr.get("feat")
    if f:
        names = [f] if isinstance(f, str) else list(f)
        return [canon(x) for x in names if x]
    return [] if tr.get("album") else others_of(tr["artist"])


def load_roles() -> dict:
    if ROLES_FILE.is_file():
        return json.loads(ROLES_FILE.read_text(encoding="utf-8"))
    return {}


def load_notes() -> dict:
    """Per-track story blocks (slug -> list of paragraphs), shown under lead."""
    if NOTES_FILE.is_file():
        return json.loads(NOTES_FILE.read_text(encoding="utf-8"))
    return {}


# track-story blocks keyed by slug; populated in main()
NOTES: dict = {}


def album_note_key(artist: str, album: str) -> str:
    """Stable key for a story that belongs to a release as a whole."""
    return f"album-{slugify(primary_of(artist), album)}"


def notes_for(tr: dict) -> list[str]:
    """Release context first, then the track-specific interview answer."""
    paragraphs: list[str] = []
    if tr.get("album"):
        paragraphs.extend(NOTES.get(album_note_key(tr["artist"], tr["album"]), []))
    paragraphs.extend(NOTES.get(tr.get("slug", ""), []))
    return paragraphs


def linkify(text: str) -> str:
    """Escape story copy while keeping supplied http(s) references useful.

    Trailing sentence punctuation is left outside the link: a URL that ends a
    sentence would otherwise carry the full stop into href and 404.
    """
    safe = esc(text)

    def wrap(m: re.Match) -> str:
        url = m.group(0)
        tail = re.search(r"[.,;:!?)»]+$", url)
        tail = tail.group(0) if tail else ""
        if tail:
            url = url[: -len(tail)]
        return f'<a href="{url}" rel="noopener" target="_blank">{url}</a>{tail}'

    return re.sub(r"https?://[^\s<]+", wrap, safe)


def story_details(paragraphs: list[str], label: str = "О работе над треком") -> str:
    if not paragraphs:
        return ""
    body = "".join(f"<p>{linkify(p)}</p>" for p in paragraphs)
    return (
        '<details class="story">'
        f'<summary>{esc(label)}</summary><div class="story-copy">{body}</div>'
        "</details>"
    )


def load_feats() -> dict:
    """Map track id -> featured artist(s) from feats.json. Value is a
    string ("SALUKI") or list (["SALUKI", "OG Buda"]); empty = no feat."""
    if not FEATS_FILE.is_file():
        return {}
    data = json.loads(FEATS_FILE.read_text(encoding="utf-8"))
    return {row["id"]: row["feat"] for row in data if row.get("feat")}


def extract_tracks(doc: str, roles: dict) -> list[dict]:
    tracks: list[dict] = []
    seen: set[str] = set()

    tile_re = re.compile(
        r'<button class="tile(?![^"]*album)[^"]*"[^>]*data-id="([A-Za-z0-9]{22})"[^>]*>'
        r'.*?<img src="([^"]+)"[^>]*>.*?<span class="art">(.*?)</span>'
        r'<span class="trk">(.*?)</span><span class="yr">(.*?)</span>',
        re.S,
    )
    for tid, img, artist, title, year in tile_re.findall(doc):
        artist = html.unescape(re.sub(r"<[^>]+>", "", artist))
        if tid in seen:
            continue
        seen.add(tid)
        tracks.append({
            "id": tid, "img": img, "artist": artist,
            "title": html.unescape(title), "year": html.unescape(year),
            "album": "", "role": roles.get(tid, "mix"),
        })

    feats = load_feats()
    albums = json.loads(re.search(r"var ALBUMS=(\[.*?\]);", doc, re.S).group(1))
    for album in albums:
        for tr in album["tracks"]:
            tid = tr["id"]
            if tid in seen:
                continue
            seen.add(tid)
            tracks.append({
                "id": tid, "img": album["cover"], "artist": album["artist"],
                "title": tr["title"], "year": tr.get("year", ""),
                "album": album["name"], "role": roles.get(tid, "mix"),
                "feat": feats.get(tid, tr.get("feat", "")),
            })

    return tracks


def assign_slugs(tracks: list[dict]) -> None:
    used: dict[str, int] = {}
    for tr in tracks:
        base = slugify(tr["artist"], tr["title"])
        n = used.get(base, 0)
        used[base] = n + 1
        tr["slug"] = base if n == 0 else f"{base}-{n + 1}"


# ── related works (внутренняя перелинковка) ──────────────────────────
#
# Страница трека раньше ссылалась только на хаб и FAQ, поэтому в Search
# Console у каждой стояло «Ссылающаяся страница: не найдено», а 179 из 220
# адресов висели в статусе «Обнаружена, не проиндексирована»: робот знал
# про них из sitemap, но не имел пути обхода и повода тратить бюджет.
# Соседи выбираются кольцом (не «первые пять»), чтобы входящие ссылки
# достались каждому треку, а не только началу списка артиста.

REL_MAX = 5


def _ring(seq: list[dict], start: int, n: int) -> list[dict]:
    """n соседей по кругу, начиная со следующего за start."""
    out = []
    for k in range(1, len(seq)):
        if len(out) >= n:
            break
        out.append(seq[(start + k) % len(seq)])
    return out


def attach_related(tracks: list[dict]) -> None:
    by_artist: "OrderedDict[str, list[dict]]" = OrderedDict()
    by_album: "OrderedDict[tuple, list[dict]]" = OrderedDict()
    for tr in tracks:
        by_artist.setdefault(primary_of(tr["artist"]), []).append(tr)
        if tr.get("album"):
            by_album.setdefault((primary_of(tr["artist"]), tr["album"]), []).append(tr)

    for group in by_album.values():
        for i, tr in enumerate(group):
            tr["rel_album"] = _ring(group, i, REL_MAX)

    for group in by_artist.values():
        for i, tr in enumerate(group):
            same = tr.get("album") or ""
            pool = [
                t for t in group
                if t is not tr and not (same and (t.get("album") or "") == same)
            ]
            tr["rel_artist"] = _ring(pool, i % len(pool), REL_MAX) if pool else []

    # одиночки (единственная работа артиста) остались бы без ссылок вовсе —
    # им кольцо по всему каталогу, чтобы страница не была тупиком
    for i, tr in enumerate(tracks):
        if not tr.get("rel_album") and not tr.get("rel_artist"):
            tr["rel_any"] = _ring(tracks, i, 4)

    # Обратный проход: пулы у соседей разного размера, поэтому кольцо со
    # смещением само по себе не покрывает всех — часть треков осталась бы
    # без входящих ссылок, то есть ровно в том состоянии, ради которого всё
    # и затевалось. Донор — сосед по артисту с самым коротким списком.
    inbound: dict[str, int] = {}
    for tr in tracks:
        for t in (tr.get("rel_album", []) + tr.get("rel_artist", [])
                  + tr.get("rel_any", [])):
            inbound[t["slug"]] = inbound.get(t["slug"], 0) + 1
    for tr in tracks:
        if inbound.get(tr["slug"]):
            continue
        donors = [t for t in by_artist[primary_of(tr["artist"])] if t is not tr]
        if not donors:
            donors = [t for t in tracks if t is not tr]
        donor = min(donors, key=lambda t: len(t.get("rel_album", []))
                    + len(t.get("rel_artist", [])) + len(t.get("rel_any", [])))
        donor.setdefault("rel_artist", []).append(tr)
        inbound[tr["slug"]] = 1


# ── track detail page ────────────────────────────────────────────────

def render_page(tr: dict) -> str:
    url = f"{SITE}/track/{tr['slug']}/"
    role = tr["role"]
    role_word = ROLE_WORD.get(role, "Сведение")
    verb = ROLE_VERB.get(role, "Кто свёл")
    has_year = bool(tr.get("year")) and tr["year"] != "альбом"
    year_bit = f" ({tr['year']})" if has_year else ""

    q = f"{verb} «{tr['title']}»?"
    title = f"{verb} «{tr['title']}» — {tr['artist']} | Podlesny Twins"
    desc = (
        f"«{tr['title']}» ({tr['artist']}) — {role_word.lower()}: "
        f"Podlesny Twins, Павел и Антон Подлесные."
    )

    album_html = f' Из альбома «{esc(tr["album"])}».' if tr.get("album") else ""
    album_plain = f" Из альбома «{tr['album']}»." if tr.get("album") else ""
    lead = (
        f"«{esc(tr['title'])}»{year_bit} — {esc(tr['artist'])}. "
        f"{role_word}: <strong>Podlesny Twins</strong> "
        f"(Павел и Антон Подлесные).{album_html}"
    )
    answer_plain = (
        f"«{tr['title']}»{year_bit} — {tr['artist']}. {role_word}: "
        f"Podlesny Twins (Павел и Антон Подлесные).{album_plain}"
    )
    story_paragraphs = notes_for(tr)
    story_plain = " ".join(story_paragraphs)

    schema = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "MusicRecording",
                "name": tr["title"],
                "url": url,
                "image": abs_img(tr["img"]),
                "byArtist": {"@type": "MusicGroup", "name": tr["artist"]},
                **({"inAlbum": {"@type": "MusicAlbum", "name": tr["album"]}}
                   if tr.get("album") else {}),
                "contributor": {
                    "@type": "Organization",
                    "@id": STUDIO_ID,
                    "name": "Podlesny Twins",
                    "url": f"{SITE}/",
                },
                "description": answer_plain + (f" {story_plain}" if story_plain else ""),
            },
            {
                "@type": "FAQPage",
                "mainEntity": [{
                    "@type": "Question", "name": q,
                    "acceptedAnswer": {"@type": "Answer", "text": answer_plain},
                }],
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Все треки",
                     "item": f"{SITE}/track/"},
                    {"@type": "ListItem", "position": 2,
                     "name": primary_of(tr["artist"]),
                     "item": f"{SITE}/track/#{slugify(primary_of(tr['artist'])) or 'artist'}"},
                    {"@type": "ListItem", "position": 3, "name": tr["title"],
                     "item": url},
                ],
            },
        ],
    }

    meta_line = f"{role_word} · {esc(tr['artist'])}" + (
        f" · {esc(tr['year'])}" if has_year else ""
    )

    note_html = "".join(
        f'\n  <p class="note">{linkify(p)}</p>' for p in story_paragraphs
    )

    artist_primary = primary_of(tr["artist"])
    artist_anchor = f"{SITE}/track/#{slugify(artist_primary) or 'artist'}"

    def rel_line(label: str, items: list[dict]) -> str:
        if not items:
            return ""
        links = " · ".join(
            f'<a href="{SITE}/track/{esc(t["slug"])}/">{esc(t["title"])}</a>'
            for t in items
        )
        return f'\n    <p><span class="alab">{label}</span>{links}</p>'

    also_html = (
        rel_line(f'Из альбома «{esc(tr["album"])}»: ', tr.get("rel_album", []))
        + rel_line(f"Ещё с {esc(artist_primary)}: ", tr.get("rel_artist", []))
        + rel_line("Ещё из портфолио: ", tr.get("rel_any", []))
    )
    if also_html:
        also_html = (
            f'\n  <nav class="also" aria-label="Другие работы студии">{also_html}\n  </nav>'
        )

    return f"""<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{GA_TAG}
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<meta name="robots" content="index, follow">
<link rel="canonical" href="{esc(url)}">
{hreflang_links(f"track/{tr['slug']}/")}<meta property="og:type" content="music.song">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:url" content="{esc(url)}">
<meta property="og:image" content="{esc(abs_img(tr['img']))}">
<meta property="og:locale" content="ru_RU">
<link rel="icon" type="image/png" href="{SITE}/favicon.png">
<script type="application/ld+json">{json.dumps(schema, ensure_ascii=False)}</script>
<style>
@import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap');
:root{{--bg:#1a1a19;--surface:#222221;--line:#34332f;--ink:#f2efef;--mut:#9a9292;--mut2:#7a7474;--red:#cf2c04}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--ink);font-family:'Work Sans',-apple-system,sans-serif;-webkit-font-smoothing:antialiased;line-height:1.55}}
.wrap{{max-width:680px;margin:0 auto;padding:40px 20px 80px}}
a{{color:inherit;text-decoration:none}}
.nav{{display:flex;justify-content:space-between;align-items:center;margin-bottom:40px}}
.nav a{{color:var(--mut);font-size:13px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;transition:color .15s}}
.nav a:hover{{color:var(--ink)}}
.nav{{gap:14px}}
.nav a:first-child{{margin-right:auto}}
.nav .pflang{{position:relative;border-left:1px solid var(--line);padding-left:14px}}
.nav .pflang::after{{content:"";position:absolute;inset:-15px -10px}}
.nav .pflang:hover,.nav .pflang:focus-visible{{color:var(--red)}}
.nav .pflang:focus-visible{{outline:2px solid var(--red);outline-offset:3px}}
.bc{{font-size:13px;color:var(--mut2);margin-bottom:22px}}
.bc a{{color:var(--mut)}}
.bc a:hover{{color:var(--ink)}}
.entry{{display:flex;gap:18px;align-items:center;margin-bottom:26px}}
.entry img{{width:96px;height:96px;border-radius:10px;object-fit:cover;flex:none}}
.meta{{font-size:13px;color:var(--red);font-weight:600;letter-spacing:.02em;margin-bottom:6px}}
h1{{font-size:clamp(26px,5vw,38px);line-height:1.08;margin:0;font-weight:700;letter-spacing:-.01em;text-wrap:balance}}
.lead{{font-size:16px;color:#cfc9c9;margin:0 0 26px;max-width:62ch}}
.lead strong{{color:var(--ink);font-weight:600}}
.note{{font-size:15px;color:var(--mut);max-width:62ch;margin:0 0 16px;padding-left:14px;border-left:2px solid var(--line)}}
.note:last-of-type{{margin-bottom:26px}}
.note a{{color:var(--red);text-decoration:underline;text-underline-offset:3px}}
.embed{{border-radius:12px;overflow:hidden;margin:0 0 28px}}
.back{{font-size:14px;color:var(--mut)}}
.back a{{color:var(--red);font-weight:600}}
.back a:hover{{text-decoration:underline}}
.also{{margin:0 0 24px}}
.also p{{font-size:13px;color:var(--mut);margin:0 0 8px;line-height:1.75;max-width:62ch}}
.also p:last-child{{margin:0}}
.alab{{color:var(--mut)}}
.also a{{white-space:nowrap;color:#cfc9c9;text-decoration:underline;text-decoration-color:var(--line);text-underline-offset:3px;transition:color .15s,text-decoration-color .15s}}
.also a:hover{{color:var(--ink);text-decoration-color:var(--red)}}
.workinfo{{font-size:13px;color:var(--mut);margin:0 0 16px}}
.workinfo a{{color:var(--red);font-weight:600}}
.workinfo a:hover{{text-decoration:underline}}
.trackfoot{{font-size:12px;color:var(--mut2);margin-top:18px;padding-top:16px;border-top:1px solid var(--line)}}
.trackfoot a{{color:var(--mut);font-weight:600}}
.trackfoot a:hover{{color:var(--ink)}}
</style>
</head>
<body>
<div class="wrap">
  <div class="nav">
    <a href="{SITE}/">Портфолио</a>
    <a href="https://podlesnytwins.com">Курс</a>
    <a class="pflang" href="{SITE}/en/track/{esc(tr['slug'])}/" hreflang="en" lang="en" aria-label="Switch to English">EN</a>
  </div>
  <div class="bc"><a href="{SITE}/">Портфолио</a> / <a href="{SITE}/track/">Все треки</a> / <a href="{esc(artist_anchor)}">{esc(artist_primary)}</a> / {esc(tr['title'])}</div>
  <div class="entry">
    <img src="{esc(tr['img'])}" alt="{esc(tr['artist'] + ' — ' + tr['title'])}">
    <div>
      <div class="meta">{meta_line}</div>
      <h1>«{esc(tr['title'])}»</h1>
    </div>
  </div>
  <p class="lead">{lead}</p>{note_html}
  <div class="embed">
    <iframe src="https://open.spotify.com/embed/track/{esc(tr['id'])}?utm_source=generator" width="100%" height="152" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy" title="Слушать «{esc(tr['title'])}»"></iframe>
  </div>{also_html}
  <p class="workinfo">Условия работы: <a href="{SITE}/faq/#what-to-send">что прислать, чтобы заказать сведение</a> · <a href="{SITE}/faq/#order">цены, сроки и правки</a></p>
  <p class="back"><a href="{SITE}/track/">← Все треки</a></p>
  <p class="trackfoot"><a href="{SITE}/faq/">Вопросы и ответы</a> · <a href="https://t.me/lesnymix" rel="noopener">Канал о звуке</a> · <a href="https://t.me/+VXgXHnAXj9w2ZGYy" rel="noopener">Чат</a></p>
</div>
</body>
</html>
"""


# ── hub (grouped reference, deduped by primary artist) ───────────────

def _artist_sort_key(name: str):
    """Latin A–Z first, then Cyrillic А–Я, then digits/other."""
    cl = (name[:1] or "").lower()
    if "a" <= cl <= "z":
        bucket = 0
    elif "а" <= cl <= "я" or cl == "ё":
        bucket = 1
    else:
        bucket = 2
    return (bucket, name.lower())


def _dq(*parts: str) -> str:
    return esc(" ".join(p for p in parts if p).lower())


def _feat(tr: dict) -> str:
    o = feat_of(tr)
    return f'<span class="feat"> · с {esc(", ".join(o))}</span>' if o else ""


def render_hub(tracks: list[dict]) -> str:
    groups: "OrderedDict[str, dict]" = OrderedDict()
    for tr in tracks:
        key = primary_of(tr["artist"])
        g = groups.setdefault(key, {"albums": OrderedDict(), "singles": [],
                                     "ia": is_ia(tr["artist"].split(", ")[0])})
        if tr.get("album"):
            alb = g["albums"].setdefault(
                tr["album"],
                {"year": tr.get("year", ""), "cover": tr["img"],
                 "tracks": [], "artist": tr["artist"]},
            )
            alb["tracks"].append(tr)
        else:
            g["singles"].append(tr)

    artists = sorted(groups, key=_artist_sort_key)
    any_ia = any(g["ia"] for g in groups.values())

    blocks = []
    prev_letter = ""
    for artist in artists:
        g = groups[artist]
        count = len(g["singles"]) + sum(len(a["tracks"]) for a in g["albums"].values())
        ia_sup = '<sup class="ia">*</sup>' if g["ia"] else ""

        letter = artist[0].upper() if artist else "#"
        if letter != prev_letter:
            prev_letter = letter
            blocks.append(f'<div class="letter">{esc(letter)}</div>')

        rels = []
        for name, alb in g["albums"].items():
            items = "".join(
                f'<li class="trk-item" data-q="{_dq(t["title"], t["artist"], name)}">'
                f'<a href="/track/{esc(t["slug"])}/">{esc(t["title"])}{_feat(t)}</a>'
                f'{story_details(NOTES.get(t["slug"], []))}</li>'
                for t in alb["tracks"]
            )
            year = f'<span class="rel-year">{esc(alb["year"])}</span>' if alb["year"] else ""
            release_story = story_details(
                NOTES.get(album_note_key(alb["artist"], name), []),
                "История альбома",
            )
            rels.append(
                '<div class="rel album">'
                f'<img class="rel-cover" src="{esc(alb["cover"])}" '
                f'alt="{esc(name + " — " + artist)}" loading="lazy" width="56" height="56">'
                '<div class="rel-body">'
                f'<div class="rel-head"><span class="rel-name">«{esc(name)}»</span>{year}'
                f'<span class="rel-kind">альбом</span></div>'
                f'{release_story}'
                f'<ol class="trk-list">{items}</ol>'
                "</div></div>"
            )

        if g["singles"]:
            label = '<div class="rel-label">Синглы</div>' if g["albums"] else ""
            rows = "".join(
                f'<div class="sg-wrap" data-q="{_dq(t["title"], t["artist"])}">'
                f'<a class="sg" href="/track/{esc(t["slug"])}/">'
                f'<img src="{esc(t["img"])}" alt="" loading="lazy" width="40" height="40">'
                f'<span class="sg-name">{esc(t["title"])}{_feat(t)}</span>'
                + (f'<span class="sg-year">{esc(t["year"])}</span>'
                   if t.get("year") and t["year"] != "альбом" else "<span></span>")
                + f'</a>{story_details(NOTES.get(t["slug"], []))}</div>'
                for t in sorted(g["singles"], key=lambda x: x["title"].lower())
            )
            rels.append(f'<div class="rel singles">{label}<div class="sg-list">{rows}</div></div>')

        aid = slugify(artist) or "artist"
        blocks.append(
            f'<section class="art-sec" id="{esc(aid)}" data-artist="{esc(artist.lower())}">'
            f'<header class="art-head"><h2>{esc(artist)}{ia_sup}</h2>'
            f'<span class="art-cnt">{count}</span></header>'
            f'{"".join(rels)}</section>'
        )

    seen_l: set[str] = set()
    jump_links = []
    for a in artists:
        L = a[0].upper() if a else "#"
        if L in seen_l:
            continue
        seen_l.add(L)
        jump_links.append(f'<a class="lj" href="#{esc(slugify(a) or "artist")}">{esc(L)}</a>')

    ia_foot = (
        '<p class="ia-foot">* признан(ы) в РФ иностранным агентом.</p>'
        if any_ia else ""
    )
    counts = catalog_counts(tracks)
    total = counts["recordings"]
    # The toolbar figure is the site-wide creditedArtistsCount (collab and
    # featured artists included), not the number of sections: the FAQ and
    # llms.txt quote the same number, and one catalogue must not give two.
    stat = (
        f"{total} {plural(total, 'трек', 'трека', 'треков')} · "
        f"{counts['artists']} {plural(counts['artists'], 'артист', 'артиста', 'артистов')}"
    )
    catalog = "".join(blocks)

    # ItemList of the whole catalogue — one structured list an answer engine
    # can read as "these are the works", plus breadcrumbs. Reuses the site's
    # existing #podlesnytwins entity id.
    item_ld = {
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "CollectionPage", "@id": f"{SITE}/track/#webpage",
             "url": f"{SITE}/track/",
             "name": "Кто свёл — все треки Podlesny Twins",
             "isPartOf": {"@id": f"{SITE}/#podlesnytwins"}},
            {"@type": "ItemList", "numberOfItems": total, "itemListOrder": "https://schema.org/ItemListUnordered",
             "itemListElement": [
                 {"@type": "ListItem", "position": i,
                  "url": f"{SITE}/track/{t['slug']}/",
                  "name": f"{t['title']} — {t['artist']}"}
                 for i, t in enumerate(tracks, 1)]},
            {"@type": "BreadcrumbList", "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Портфолио", "item": f"{SITE}/"},
                {"@type": "ListItem", "position": 2, "name": "Все треки", "item": f"{SITE}/track/"}]},
        ],
    }
    item_ld_json = json.dumps(item_ld, ensure_ascii=False)
    return f"""<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{GA_TAG}
<title>Кто свёл — все треки Podlesny Twins</title>
<meta name="description" content="Справочник работ Podlesny Twins: альбомы и треки, над которыми работали Павел и Антон Подлесные (сведение и мастеринг). {total} треков с поиском по артисту и названию.">
<link rel="canonical" href="{SITE}/track/">
{hreflang_links("track/")}<link rel="icon" type="image/png" href="{SITE}/favicon.png">
<script type="application/ld+json">{item_ld_json}</script>
<style>
@import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap');
@font-face{{font-family:'SaarSP';src:url('https://static.tildacdn.com/tild6565-6366-4065-b536-663938373766/SaarSPDemo.WOFF') format('woff');font-weight:400;font-display:swap}}
:root{{--bg:#1a1a19;--surface:#222221;--surface2:#2a2a28;--line:#34332f;--line2:#2a2a28;--ink:#f2efef;--mut:#9a9292;--mut2:#7a7474;--red:#cf2c04}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--ink);font-family:'Work Sans',-apple-system,sans-serif;-webkit-font-smoothing:antialiased;line-height:1.5}}
.pf{{max-width:940px;margin:0 auto;padding:48px 20px 96px}}
a{{color:inherit;text-decoration:none}}
.pfnav{{display:flex;justify-content:space-between;align-items:center;padding-bottom:18px;margin-bottom:40px;border-bottom:1px solid var(--line)}}
.pflink{{color:var(--mut);font-weight:600;font-size:13px;letter-spacing:.04em;text-transform:uppercase;transition:color .15s}}
.pflink:hover{{color:var(--ink)}}
.pfnav{{gap:14px}}
.pfnav .pflink:first-child{{margin-right:auto}}
.pflang{{position:relative;border-left:1px solid var(--line);padding-left:14px}}
.pflang::after{{content:"";position:absolute;inset:-15px -10px}}
.pflang:hover,.pflang:focus-visible{{color:var(--red)}}
.pflang:focus-visible{{outline:2px solid var(--red);outline-offset:3px}}
h1{{font-family:'SaarSP',Arial,sans-serif;font-weight:400;font-size:clamp(36px,7vw,68px);line-height:.92;margin:0 0 14px;letter-spacing:-.01em}}
.lead{{font-size:16px;color:var(--mut);max-width:58ch;margin:0}}
.toolbar{{display:flex;flex-wrap:wrap;gap:14px;align-items:center;margin:30px 0 6px}}
.search{{flex:1;min-width:220px;background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:13px 16px;color:var(--ink);font:inherit;font-size:15px;outline:none;transition:border-color .15s}}
.search::placeholder{{color:var(--mut2)}}
.search:focus{{border-color:var(--red)}}
.stat{{font-size:13px;color:var(--mut);font-variant-numeric:tabular-nums;white-space:nowrap}}
.jump{{display:flex;flex-wrap:wrap;gap:4px;margin:14px 0 0}}
.lj{{display:inline-flex;align-items:center;justify-content:center;min-width:30px;height:30px;padding:0 8px;border-radius:8px;color:var(--mut);font-size:12px;font-weight:700;transition:.15s}}
.lj:hover{{color:var(--ink);background:var(--surface)}}
.catalog{{margin-top:30px}}
.letter{{font-family:'SaarSP',Arial,sans-serif;font-size:22px;color:var(--red);margin:40px 0 6px;padding-bottom:8px;border-bottom:1px solid var(--line)}}
.letter:first-child{{margin-top:0}}
.art-sec{{padding:20px 0;border-top:1px solid var(--line2)}}
.art-sec:first-of-type,.letter + .art-sec{{border-top:0}}
.art-head{{display:flex;align-items:baseline;gap:10px;margin-bottom:12px}}
.art-head h2{{margin:0;font-size:19px;font-weight:700;letter-spacing:-.01em}}
.art-head sup{{font-size:11px;color:var(--mut2)}}
.art-cnt{{font-size:12px;color:var(--mut2);font-variant-numeric:tabular-nums}}
.rel{{padding:8px 0}}
.rel.album{{display:flex;gap:14px}}
.rel-cover{{width:56px;height:56px;border-radius:8px;object-fit:cover;flex:none}}
.rel-body{{flex:1;min-width:0}}
.rel-head{{display:flex;align-items:baseline;gap:10px;margin-bottom:8px;flex-wrap:wrap}}
.rel-name{{font-size:15px;font-weight:600}}
.rel-year{{font-size:12px;color:var(--mut);font-variant-numeric:tabular-nums}}
.rel-kind{{font-size:11px;color:var(--mut2);letter-spacing:.06em;text-transform:uppercase}}
.rel-label{{font-size:13px;color:var(--mut);margin-bottom:4px}}
.feat{{color:var(--mut2);font-weight:400}}
.trk-list{{list-style:none;margin:0;padding:0;counter-reset:t;column-width:230px;column-gap:30px}}
.trk-list li{{counter-increment:t;break-inside:avoid}}
.trk-list a{{display:flex;gap:10px;padding:4px 0;font-size:14px;color:#d8d2d2;transition:color .12s}}
.trk-list a::before{{content:counter(t);color:var(--mut2);font-size:12px;font-variant-numeric:tabular-nums;min-width:1.7em;text-align:right;flex:none}}
.trk-list a:hover{{color:var(--red)}}
.sg-list{{display:flex;flex-direction:column}}
.sg-wrap{{border-top:1px solid var(--line2)}}
.sg-wrap:first-child{{border-top:0}}
.sg{{display:grid;grid-template-columns:40px 1fr auto;align-items:center;gap:12px;padding:7px 0}}
.sg img{{width:40px;height:40px;border-radius:6px;object-fit:cover;display:block}}
.sg-name{{font-size:14px;font-weight:500;min-width:0;transition:color .12s}}
.sg-year{{font-size:12px;color:var(--mut);font-variant-numeric:tabular-nums}}
.sg:hover .sg-name{{color:var(--red)}}
.story{{margin:3px 0 10px;max-width:72ch}}
.story summary{{display:flex;align-items:center;min-height:36px;width:max-content;max-width:100%;color:var(--mut);font-size:12px;font-weight:600;cursor:pointer;list-style:none;transition:color .15s}}
.story summary::-webkit-details-marker{{display:none}}
.story summary::after{{content:"";width:6px;height:6px;margin-left:8px;border-right:1px solid currentColor;border-bottom:1px solid currentColor;transform:rotate(45deg) translateY(-2px);transition:transform .2s cubic-bezier(.2,.8,.2,1)}}
.story[open] summary{{color:var(--red)}}
.story[open] summary::after{{transform:rotate(225deg) translate(-1px,-1px)}}
.story-copy{{padding:2px 0 5px;color:#aaa3a3;font-size:13px;line-height:1.62;max-width:68ch}}
.story-copy p{{margin:0 0 9px}}
.story-copy p:last-child{{margin-bottom:0}}
.story-copy a{{color:var(--red);text-decoration:underline;text-underline-offset:3px}}
.rel > .rel-body > .story{{margin:-2px 0 8px}}
.ia-foot{{margin-top:40px;font-size:12px;color:var(--mut2)}}
.hublead{{font-size:14px;color:var(--mut);max-width:58ch;margin:10px 0 0}}
.hublead a{{color:var(--red);font-weight:600}}
.hubfoot{{margin-top:40px;padding-top:18px;border-top:1px solid var(--line);font-size:13px;color:var(--mut2)}}
.hubfoot a{{color:var(--mut);font-weight:600}}
.hubfoot a:hover{{color:var(--ink)}}
.hide{{display:none!important}}
.empty{{display:none;text-align:center;padding:56px 20px;color:var(--mut);font-size:15px}}
.empty.on{{display:block}}
@media (max-width:560px){{
.pf{{padding:32px 14px 64px}}
.rel.album{{gap:11px}}
.rel-cover{{width:48px;height:48px}}
.trk-list{{column-width:auto}}
.story summary{{min-height:44px}}
}}
@media (prefers-reduced-motion:reduce){{*{{transition:none!important}}}}
</style>
</head>
<body>
<div class="pf">
  <div class="pfnav">
    <a class="pflink" href="{SITE}/">← Портфолио</a>
    <a class="pflink" href="https://podlesnytwins.com">Курс →</a>
    <a class="pflink pflang" href="{SITE}/en/track/" hreflang="en" lang="en" aria-label="Switch to English">EN</a>
  </div>
  <h1>Кто свёл</h1>
  <p class="lead">Альбомы и треки из нашего портфолио — сведение и мастеринг. Ищите по артисту, альбому или названию.</p>
  <p class="hublead">Полный каталог работ студии. Условия заказа сведения и мастеринга — в разделе <a href="{SITE}/faq/">вопросов и ответов</a>.</p>
  <div class="toolbar">
    <input class="search" id="q" type="search" placeholder="Артист, альбом или трек…" autocomplete="off">
    <span class="stat">{stat}</span>
  </div>
  <nav class="jump" aria-label="По алфавиту">{"".join(jump_links)}</nav>
  <div class="catalog" id="catalog">{catalog}</div>
  <p class="empty" id="empty">Ничего не нашлось</p>
  {ia_foot}
  <p class="hubfoot"><a href="{SITE}/faq/">Вопросы и ответы</a> · <a href="https://t.me/lesnymix" rel="noopener">Канал о звуке</a> · <a href="https://t.me/+VXgXHnAXj9w2ZGYy" rel="noopener">Чат</a></p>
</div>
<script>
(function(){{
  var q=document.getElementById('q'),cat=document.getElementById('catalog'),em=document.getElementById('empty');
  function norm(s){{return (s||'').toLowerCase().replace(/ё/g,'е');}}
  function run(){{
    var v=norm(q.value.trim()),any=false;
    cat.querySelectorAll('.art-sec').forEach(function(sec){{
      var aMatch=norm(sec.getAttribute('data-artist')).indexOf(v)>=0,secShow=false;
      sec.querySelectorAll('.rel').forEach(function(rel){{
        var relShow=false;
        rel.querySelectorAll('[data-q]').forEach(function(it){{
          var ok=!v||aMatch||norm(it.getAttribute('data-q')).indexOf(v)>=0;
          it.classList.toggle('hide',!ok); if(ok) relShow=true;
        }});
        rel.classList.toggle('hide',!relShow);
        if(relShow) secShow=true;
      }});
      sec.classList.toggle('hide',!secShow);
      if(secShow) any=true;
    }});
    cat.querySelectorAll('.letter').forEach(function(l){{
      var n=l.nextElementSibling,show=false;
      while(n&&!n.classList.contains('letter')){{
        if(n.classList.contains('art-sec')&&!n.classList.contains('hide')){{show=true;break;}}
        n=n.nextElementSibling;
      }}
      l.classList.toggle('hide',!show);
    }});
    em.classList.toggle('on',!any);
  }}
  q.addEventListener('input',run);
}})();
</script>
</body>
</html>
"""


def patch_index_footer(doc: str, tracks: list[dict]) -> str:
    css = """
.pf .seo-foot{margin:22px auto 0;font-size:12px;line-height:1.5}
.pf .seo-foot a{color:#918b8b;font-weight:600}
.pf .seo-foot a:hover{color:#cfc9c9}
"""
    if ".pf .seo-foot" not in doc:
        doc = doc.replace("</style>", css + "</style>", 1)

    # The home-page footer links out to the catalogue, the FAQ, and the
    # studio's Telegram channel + chat. Replace the whole <p class="seo-foot">
    # in place (idempotent) so re-runs update it instead of duplicating.
    foot = ('<p class="seo-foot"><a href="/track/">Полный список треков</a>'
            ' · <a href="/faq/">Вопросы и ответы</a>'
            ' · <a href="/tier/">Тир-лист техник сведения</a>'
            ' · <a href="https://t.me/lesnymix" rel="noopener">Канал о звуке</a>'
            ' · <a href="https://t.me/+VXgXHnAXj9w2ZGYy" rel="noopener">Чат</a></p>')
    if 'class="seo-foot"' in doc:
        doc = re.sub(r'<p class="seo-foot">.*?</p>', foot, doc, count=1, flags=re.S)
    else:
        doc = doc.replace('<p class="iadisc">', foot + "\n    " + '<p class="iadisc">', 1)

    # One source of truth for the card-side story viewer. Only works that
    # actually have a story are listed: the modal never opens without one.
    #
    # The texts (≈140 KB) live in /track-info.json, not inline — the grid is
    # the page's whole promise and pays for its own weight; the stories are
    # fetched once the page is idle, long before anyone opens one. Inline
    # stays the id list, so the ⓘ buttons can be placed on first paint.
    track_info = {
        tr["id"]: {
            "slug": tr["slug"],
            "artist": tr["artist"],
            "title": tr["title"],
            "year": tr.get("year", ""),
            "role": ROLE_WORD.get(tr["role"], "Сведение"),
            "notes": notes_for(tr),
            "url": f"/track/{tr['slug']}/",
            "image": tr.get("img", ""),
        }
        for tr in tracks
        if notes_for(tr)
    }
    (ROOT / "track-info.json").write_text(
        json.dumps(track_info, ensure_ascii=False, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )

    ids = json.dumps(sorted(track_info), separators=(",", ":"))
    data_tag = f'<script type="application/json" id="track-story-ids">{ids}</script>'
    doc = re.sub(                       # the earlier inline payload, if present
        r'<script type="application/json" id="track-info-data">.*?</script>\n?',
        "",
        doc,
        count=1,
        flags=re.S,
    )
    if 'id="track-story-ids"' in doc:
        doc = re.sub(
            r'<script type="application/json" id="track-story-ids">.*?</script>',
            data_tag,
            doc,
            count=1,
            flags=re.S,
        )
    else:
        doc = doc.replace(
            '<script src="https://open.spotify.com/embed/iframe-api/v1" async></script>',
            data_tag + '\n<script src="https://open.spotify.com/embed/iframe-api/v1" async></script>',
            1,
        )
    doc = patch_index_roles(doc, tracks)
    return patch_hreflang(doc, "")


# ── home page: role-accurate alts + JSON-LD catalogue ────────────────
#
# add_track.py writes every new tile with the generic «сведение и мастеринг»
# alt, and the home-page JSON-LD was maintained by hand (it had drifted: 8
# singles and one album missing, every Role claiming both jobs). roles.json is
# the only place a role is recorded, so both are rewritten from it here on
# every build — the alt tail and the Role.roleName can no longer over-claim.

LD_BYLINE = "Podlesny Twins (Павел Подлесный и Антон Подлесный)"


def _studio_role(role: str) -> dict:
    return {"@type": "Role", "roleName": ROLE_NAME_LD[role],
            "contributor": {"@id": STUDIO_ID}}


def _recording_ld(tr: dict, with_description: bool) -> dict:
    node = {
        "@type": "MusicRecording",
        "name": tr["title"],
        "url": f"{SITE}/track/{tr['slug']}/",
        "byArtist": {"@type": "MusicGroup", "name": tr["artist"]},
        "contributor": _studio_role(tr["role"]),
    }
    if with_description:
        node["description"] = f"{ROLE_WORD[tr['role']]} — {LD_BYLINE}."
    return node


def _album_roles(album: dict, by_id: dict) -> set[str]:
    return {by_id[t["id"]]["role"] for t in album["tracks"] if t["id"] in by_id}


def patch_index_roles(doc: str, tracks: list[dict]) -> str:
    by_id = {tr["id"]: tr for tr in tracks}
    albums = json.loads(re.search(r"var ALBUMS=(\[.*?\]);", doc, re.S).group(1))

    # 1. cover alts. Single: «Artist — Title · <role> Podlesny Twins».
    #    Album: same with «(альбом)» when every track shares one role; a
    #    release with mixed roles names the cover and claims nothing.
    def single_alt(m: re.Match) -> str:
        tid = m.group(2)
        tr = by_id.get(tid)
        if tr is None:
            return m.group(0)
        alt = f"{tr['artist']} — {tr['title']} · {ROLE_ALT[tr['role']]}"
        return f"{m.group(1)}{esc(alt)}{m.group(3)}"

    doc = re.sub(
        r'(<button class="tile(?![^"]*album)[^"]*"[^>]*data-id="([A-Za-z0-9]{22})"'
        r'[^>]*>\s*<img src="[^"]+" alt=")[^"]*(")',
        single_alt, doc,
    )

    def album_alt(m: re.Match) -> str:
        album = albums[int(m.group(2))]
        roles = _album_roles(album, by_id)
        head = f"{album['artist']} — {album['name']} (альбом)"
        tail = ROLE_ALT[roles.pop()] if len(roles) == 1 else MIXED_ALT
        return f"{m.group(1)}{esc(f'{head} · {tail}')}{m.group(3)}"

    doc = re.sub(
        r'(<button class="tile album"[^>]*onclick="openAlbum\((\d+)\)"[^>]*>\s*'
        r'<img src="[^"]+" alt=")[^"]*(")',
        album_alt, doc,
    )

    # 2. JSON-LD: studio entity (normalised) + founders, then the catalogue
    #    regenerated from the tiles, so it lists exactly what the page shows.
    ld_re = re.compile(r'(<script type="application/ld\+json">)(.*?)(</script>)', re.S)
    m = ld_re.search(doc)
    if not m:
        raise SystemExit("index.html: JSON-LD block not found")
    graph = json.loads(m.group(2))["@graph"]
    head = fix_studio_graph([n for n in graph if n.get("@type") not in ("MusicRecording", "MusicAlbum")])

    catalogue: list[dict] = []
    for tr in tracks:
        if not tr.get("album"):
            catalogue.append(_recording_ld(tr, with_description=True))
    for album in albums:
        roles = _album_roles(album, by_id)
        node = {
            "@type": "MusicAlbum",
            "name": album["name"],
            "byArtist": {"@type": "MusicGroup", "name": album["artist"]},
        }
        if len(roles) == 1:
            role = next(iter(roles))
            node["contributor"] = _studio_role(role)
            node["description"] = f"{ROLE_WORD[role]} — {LD_BYLINE}."
        else:
            node["description"] = f"Роль студии указана по каждому треку — {LD_BYLINE}."
        node["track"] = [
            _recording_ld(by_id[t["id"]], with_description=False)
            for t in album["tracks"] if t["id"] in by_id
        ]
        catalogue.append(node)

    ld = json.dumps({"@context": "https://schema.org", "@graph": head + catalogue},
                    ensure_ascii=False)
    return doc[: m.start(2)] + ld + doc[m.end(2):]


# ── FAQ + llms.txt: counters and the studio entity from one source ───
#
# Both files are hand-written, so the figures used to be typed in and went
# stale (214/69 against a 217-track catalogue). The numbers now live in
# <span data-n="works|artists"> markers in the FAQ and in one fixed phrase
# in llms.txt; the build rewrites them from catalog_counts() and refuses to
# continue if a marker disappeared — a silent miss is how they drifted.

FAQ_FILE = ROOT / "faq" / "index.html"
LLMS_FILE = ROOT / "llms.txt"


def _sub_counted(text: str, pattern: str, repl, label: str, min_hits: int = 1) -> str:
    out, n = re.subn(pattern, repl, text)
    if n < min_hits:
        raise SystemExit(f"{label}: expected ≥{min_hits} counter marker(s), found {n}")
    return out


def patch_faq(counts: dict) -> None:
    src = FAQ_FILE.read_text(encoding="utf-8")
    for key, value in (("works", counts["recordings"]), ("artists", counts["artists"])):
        src = _sub_counted(
            src, rf'(<span(?=[^>]*\bdata-n="{key}")[^>]*>)\d+(</span>)',
            rf"\g<1>{value}\g<2>", f"faq/index.html data-n={key}",
        )
    ld_re = re.compile(r'(<script type="application/ld\+json">)(.*?)(</script>)', re.S)
    m = ld_re.search(src)
    if not m:
        raise SystemExit("faq/index.html: JSON-LD block not found")
    data = json.loads(m.group(2))
    data["@graph"] = fix_studio_graph(data["@graph"])
    src = src[: m.start(2)] + json.dumps(data, ensure_ascii=False) + src[m.end(2):]
    src = patch_hreflang(src, "faq/")
    FAQ_FILE.write_text(src, encoding="utf-8")
    # the FAQPage answers are copies of the visible text — rebuild them now
    # so the counters just written land in the schema in the same run
    import sync_faq_schema
    if sync_faq_schema.main() != 0:
        raise SystemExit("sync_faq_schema failed")


def patch_llms_txt(counts: dict) -> None:
    src = LLMS_FILE.read_text(encoding="utf-8")
    src = _sub_counted(
        src, r"\d+ избранных работ для \d+ артистов",
        f"{counts['recordings']} избранных работ для {counts['artists']} артистов",
        "llms.txt",
    )
    en_line = (f"- [English version](https://credits.podlesnytwins.com/en/): "
               f"страницы на английском; сводка для ИИ — {SITE}/en/llms.txt")
    if en_exists("") and "/en/llms.txt" not in src:
        anchor = f"- [llms-full.txt]({SITE}/llms-full.txt)"
        i = src.find(anchor)
        if i < 0:
            raise SystemExit("llms.txt: «Полный контент» anchor line not found")
        j = src.find("\n", i)
        src = src[: j + 1] + en_line + "\n" + src[j + 1:]
    LLMS_FILE.write_text(src, encoding="utf-8")


# ── SEO ledger: stable URLs + honest lastmod across full rebuilds ────

def content_hash(tr: dict) -> str:
    """Fingerprint the meaningful, user-visible content of a track page.

    Ignores template/CSS churn on purpose — only real content changes
    (title/artist/year/role/feat/album/cover/notes) bump the fingerprint,
    so a cosmetic template edit doesn't reset every page's <lastmod>.
    """
    payload = json.dumps(
        {
            "artist": tr.get("artist", ""), "title": tr.get("title", ""),
            "year": tr.get("year", ""), "role": tr.get("role", ""),
            "feat": tr.get("feat", ""), "album": tr.get("album", ""),
            "img": tr.get("img", ""), "notes": notes_for(tr),
        },
        ensure_ascii=False, sort_keys=True,
    )
    return hashlib.sha1(payload.encode("utf-8")).hexdigest()[:16]


def render_redirect(target_slug: str) -> str:
    """A retired slug's page: canonical + instant redirect to the live URL.

    Google treats a same-host meta-refresh(0)+canonical as a 301, so link
    equity from an old URL flows to the renamed track instead of 404-ing.
    """
    url = f"{SITE}/track/{target_slug}/"
    return (
        '<!DOCTYPE html>\n<html lang="ru">\n<head>\n<meta charset="utf-8">\n'
        f'<title>Переехало → {esc(target_slug)}</title>\n'
        f'<link rel="canonical" href="{esc(url)}">\n'
        f'<meta http-equiv="refresh" content="0; url={esc(url)}">\n'
        f'<script>location.replace({json.dumps(url)});</script>\n'
        f'</head>\n<body>\n<p>Страница переехала: <a href="{esc(url)}">{esc(url)}</a></p>\n'
        '</body>\n</html>\n'
    )


def sync_seo_state(tracks: list[dict]) -> tuple[dict, dict]:
    """Reconcile the persistent SEO ledger against the current track set.

    Returns (lastmod_by_slug, redirects). A renamed track (same data-id,
    new slug) retires its old slug into `redirects`; a removed track is
    left to 404. Chains collapse to the final live slug; redirects whose
    key is now a live slug or whose target is gone are dropped.
    """
    try:
        state = json.loads(SEO_STATE_FILE.read_text(encoding="utf-8"))
    except (FileNotFoundError, ValueError):
        state = {}
    prev_ids = state.get("ids", {})
    prev_dates = state.get("dates", {})
    redirects = dict(state.get("redirects", {}))

    live_slugs = {tr["slug"] for tr in tracks}
    cur_ids = {tr["id"]: tr["slug"] for tr in tracks}

    # retire slugs of tracks that changed slug but still exist
    for tid, old_slug in prev_ids.items():
        new_slug = cur_ids.get(tid)
        if new_slug and new_slug != old_slug:
            redirects[old_slug] = new_slug

    # collapse chains a→b→c into a→c
    def resolve(slug: str, _seen: set) -> str:
        while slug in redirects and slug not in _seen:
            _seen.add(slug)
            slug = redirects[slug]
        return slug

    redirects = {old: resolve(dst, {old}) for old, dst in redirects.items()}
    # drop redirects that collide with a live page or point nowhere live
    redirects = {
        old: dst for old, dst in redirects.items()
        if old not in live_slugs and dst in live_slugs
    }

    # honest lastmod: keep stored date unless content fingerprint changed
    dates: dict[str, str] = {}
    new_dates: dict[str, dict] = {}
    for tr in tracks:
        slug, h = tr["slug"], content_hash(tr)
        prev = prev_dates.get(slug)
        lastmod = prev["lastmod"] if prev and prev.get("hash") == h else TODAY
        dates[slug] = lastmod
        new_dates[slug] = {"hash": h, "lastmod": lastmod}

    SEO_STATE_FILE.write_text(
        json.dumps(
            {"ids": cur_ids, "redirects": redirects, "dates": new_dates},
            ensure_ascii=False, indent=1, sort_keys=True,
        ) + "\n",
        encoding="utf-8",
    )
    return dates, redirects


def _sitemap_url(rel: str, lastmod: str, changefreq: str, priority: str) -> list[str]:
    """One <url> for the RU page and, once the EN mirror exists, one for
    /en/<rel> (same lastmod: the EN page is a rendering of the same data)."""
    lines = []
    for loc in (f"{SITE}/{rel}", *([f"{SITE}/en/{rel}"] if en_exists(rel) else [])):
        lines += [
            "  <url>", f"    <loc>{loc}</loc>", f"    <lastmod>{lastmod}</lastmod>",
            f"    <changefreq>{changefreq}</changefreq>",
            f"    <priority>{priority}</priority>", "  </url>",
        ]
    return lines


def write_sitemap(tracks: list[dict], dates: dict) -> None:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        *_sitemap_url("", TODAY, "weekly", "1.0"),
        *_sitemap_url("track/", TODAY, "weekly", "0.9"),
        # /faq/ is hand-written (not generated from tracks) — its lastmod must reflect
        # when the FAQ text actually changed, not every rebuild. Bump FAQ_LASTMOD by hand.
        *_sitemap_url("faq/", FAQ_LASTMOD, "monthly", "0.8"),
        *_sitemap_url("tier/", TIER_LASTMOD, "monthly", "0.8"),
    ]
    for tr in tracks:
        lines += _sitemap_url(f"track/{tr['slug']}/", dates.get(tr["slug"], TODAY),
                              "monthly", "0.7")
    lines.append("</urlset>")
    (ROOT / "sitemap.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    global NOTES
    roles = load_roles()
    NOTES = load_notes()
    doc = INDEX.read_text(encoding="utf-8")
    tracks = extract_tracks(doc, roles)
    assign_slugs(tracks)
    attach_related(tracks)

    hub_file = TRACK_DIR / "index.html"
    if TRACK_DIR.exists():
        if hub_file.is_file():
            hub_file.unlink()
        for old in TRACK_DIR.iterdir():
            if old.is_dir():
                for f in old.iterdir():
                    f.unlink()
                old.rmdir()
    TRACK_DIR.mkdir(exist_ok=True)

    live_slugs = {tr["slug"] for tr in tracks}
    for tr in tracks:
        out = TRACK_DIR / tr["slug"]
        out.mkdir(parents=True, exist_ok=True)
        (out / "index.html").write_text(render_page(tr), encoding="utf-8")

    # reconcile SEO ledger, then re-emit redirect stubs for retired slugs
    # (the track/ wipe above deletes them each build, so rebuild from state)
    dates, redirects = sync_seo_state(tracks)
    for old_slug, new_slug in redirects.items():
        if old_slug in live_slugs:
            continue
        out = TRACK_DIR / old_slug
        out.mkdir(parents=True, exist_ok=True)
        (out / "index.html").write_text(render_redirect(new_slug), encoding="utf-8")

    hub_file.write_text(render_hub(tracks), encoding="utf-8")
    INDEX.write_text(patch_index_footer(doc, tracks), encoding="utf-8")

    counts = catalog_counts(tracks)
    patch_faq(counts)
    patch_llms_txt(counts)

    write_sitemap(tracks, dates)
    from collections import Counter
    print(f"Сгенерировано страниц: {len(tracks)}  роли: {dict(Counter(t['role'] for t in tracks))}")
    print(f"Счётчики: работ {counts['recordings']} · артистов (с соавторами и фитами) "
          f"{counts['artists']} · разделов хаба {counts['groups']}")
    if redirects:
        print(f"Редиректы (retired slugs): {len(redirects)}")

    # the EN mirror is a rendering of the pages just written; it runs here so
    # that one command keeps both sides in sync (`--no-en` to skip)
    if "--no-en" not in sys.argv:
        import subprocess
        sys.stdout.flush()
        r = subprocess.run([sys.executable, str(ROOT / "build_en.py")], cwd=ROOT)
        if r.returncode != 0:
            sys.exit(f"build_en.py завершился с кодом {r.returncode} — см. i18n/missing.txt")


if __name__ == "__main__":
    main()
